<?php
    
    $config_file_default    = "config.default";    
    $config_file_directory  = "";	
    $config_file_name       = "config.inc.php";    
    $config_file_path       = $config_file_directory.$config_file_name;
    
    $application_name       = "Join Mozilla Tunisia";
    $application_start_file = "../";
    
    $license_agreement_page = "";
    
    $sql_dump               = "db_dump.sql";
    
?>
